# Header
menu:
  首页: /
  归档: /archives
  游戏: /2048
  项目: https://github.com/w3cay

# Title on top left of menu. Leave empty to use main blog title
menu_title: Bright's Blog
title: Bright's Blog

# URL of the Home page image
index_cover:

# Default post title
default_post_title: Bright's Blog

# Comments. Choose one by filling up the information.
comments:
  # Disqus comments
  duoshuo_shortname: brightchen
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Analytics
analytics: true

# Addthis ID
addthis:
rss: /atom.xml
# Social Accounts
weibo_url: http://weibo.com/633012550
twitter_handle:
facebook_url:
github_url: https://github.com/w3cay
gitlab_url:
zhihu_url: http://zhihu.com/people/bright-chen
mailto: w3cay@foxmail.com
favicon: favicon.ico
