# Header
menu:
  Home: /
  Archives: /archives

# Title on top left of menu. Leave empty to use main blog title
menu_title: Bright Chen 

# URL of the Home page image
index_cover: http://ocqgx7uz0.bkt.clouddn.com/city-art-graffiti-wall-large-1.jpg

# Default post title
default_post_title: Bright Chen

# Comments. Choose one by filling up the information.
comments:
  # Disqus comments
  duoshuo_shortname: brightchen
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# Social Accounts
weibo_url: http://weibo.com/633012550
twitter_handle:
facebook_url:
github_url: https://github.com/w3cay
gitlab_url:
linkedin_url: http://www.linkedin.com/in/bright-chen
mailto: w3cay@foxmail.com